name: Build Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Use a GitHub-hosted runner (ubuntu-22.04 is supported)
    runs-on: ubuntu-22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Ruby environment with version 3.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true  # Cache Bundler dependencies to speed up future runs

      # Install the required gems using Bundler
      - name: Install dependencies
        run: bundle install

      # Build the Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # Optionally, you can add deployment or other steps here
      # - name: Deploy to GitHub Pages
      #   run: bundle exec jekyll serve --detach

